### ISSUE TITLE
run error?

### ISSUE THREAD

**Issue by QAbot-zh** [PavelTrutman/Global-7DOF-IKT#1]
I run the code in my matlab(2018a), and I got the error :
```
>> KUKA_LBR_GB
Error using save
Variable 'Mh' not found.

Error in KUKA_LBR_GB (line 18)
save(MhFile, 'Mh');
```
So maybe the manipulator.mat is not the correct ?

**Comment by PavelTrutman** [comment]
Hi,
thanks for letting me know. I have fixed it now. If you encounter any other error or need additional help, do not hesitate and let me know.

Thanks.

**Comment by REXINWANGYOUADONG** [comment]
HI,I run the code in my matlab(2021b), and I have installed the necessary toolbox. When I run gloptipoly.M，I got the error :
`Unrecognized function or variable 'mpol'.

Error in gloptipoly (line 36)
mpol('c', 7);
 `
I can't find the mpol function in the downloaded code, is this function in some toolbox?
