### ISSUE TITLE
For help with GB.M and gloptipoly.m

### ISSUE THREAD

**Issue by Umbrella9919** [PavelTrutman/Global-7DOF-IKT#2]
HI,I run the code in my matlab(2021b), and I have installed the necessary toolbox. When I run gloptipoly.M，I got the error :
```
Unrecognized function or variable 'mpol'.
Error in gloptipoly (line 36)
mpol('c', 7);
```
 I can't find the mpol function in the downloaded code, is this function in some toolbox?
When I run GB.M，I got the error :
```
GB
'touch' is not an internal or external command, nor is it a runnable program 
or batch file. 
'maple' is not an internal or external command, nor is it a runnable program 
or batch file. 
Wrong use of GB (line 39)
'maple' is not an internal or external command, nor is it a runnable program
or batch file.
```
I think I may need to set up the software, but maybe I didn't find it and would like some help

**Comment by Umbrella9919** [comment]
There is no mpol mdsp mset msol function in the code

**Comment by PavelTrutman** [comment]
Hi,
the `mpol` function is part of the Gloptipoly toolbox. Are you sure you have installed it correctly?
